[versions]
## SDK Versions
android-minSdk = "24"
android-compileSdk = "36"

# Dependencies
coroutines = "1.10.2"
gradle = "8.7.3"
ktor = "3.4.0"
powersync = "1.10.4"
supabase = "3.3.0"
junit = "4.13.2"

# Sample - Android
androidx-espresso-core = "3.7.0"
junitVersion = "1.3.0"

# Plugins
# Downgraded to 8.7.3 for Capacitor 6 compatibility
android-gradle-plugin = "8.7.3"
kotlin = "2.3.0"

[libraries]
# PowerSync
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
powersync-core = { module = "com.powersync:core-android", version.ref = "powersync" }
powersync-common = { module = "com.powersync:common-android", version.ref = "powersync" }
powersync-connector-supabase = { module = "com.powersync:connector-supabase-android", version.ref = "powersync" }

# Supabase
supabase-client = { module = "io.github.jan-tennert.supabase:postgrest-kt", version.ref = "supabase" }
supabase-auth = { module = "io.github.jan-tennert.supabase:auth-kt", version.ref = "supabase" }

# Ktor
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }

# Coroutines
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

# Testing
test-junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
